# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bac2d889f367a0c0e4c321bc0603cd5de28e1b5f5749df78ef61f261a87cb51cc54365bde16f2041fd0da032d4079a19f3b3b7a9cd29a6736373d24ef5367eba

test:
  secret_key_base: d076b8fde6d4ab2c1e6c7120c4ac28880c251d5f1cfa29672441015e619e424babb5361235769d787cc3528b6d1691a24fab8750c552d23d19d1cac60996e28b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
